# Main page information
cv: static/research/Vivian_John__1-4-19.pdf
bio_pic: static/img/main/me.jpg


# Visualization Links
visualizations:

  drug_sankey:
    label: Antineoplastic Biomarker Relationship
    link: static/visualizations/Sankey-Diagram-Drug-Biomarkers.html

  type_heatmap:
    label: TCGA and GTEx Differential Expression Heatmap
    link: static/visualizations/TCGA-GTEx-DE-Type-HeatMap.html

  trimap_tissues:
    label: Dimensionality Reduction of TCGA and GTEx Tissues
    link: static/visualizations/Trimap-of-Tissues.html


# Research Links
research:

    defense:
      label: Defense slides
      link: static/defense/Defense-talk-June-6-2019.pdf

    workflow:
      label: Scalable RNA-seq Expression Workflow
      link: https://github.com/BD2KGenomics/toil-rnaseq/

    advancement:
      label: PhD Advancement Proposal
      link: static/research/Vivian_J__Advancement_Proposal__Rev1.pdf

    capstone:
      label: Master's Capstone
      link: static/research/Vivian_MS_Capstone_2014.pdf

    nih_poster:
      label: NIH Poster
      link: static/research/Vivian_NIH_Poster.pdf

    stanford_poster:
      label: Stanford GTEx Poster
      link: static/research/stanford-gtex-poster.pdf

# Hobby Links
hobby:

    books:
      label: Books
      link: https://1drv.ms/o/s!AiirpWvlh1BpjAOtC2KjMTTVyxu1

    ml:
      label: Machine Learning
      link: https://github.com/jvivian/Children-of-Skynet/

# Post Links
posts:

  europe:
    label: Europe 2017 Trip
    link: static/archived_content/europe-2017.html


