name: japan
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - geopandas
  - matplotlib
  - shapely
  - pandas
  - jupyterlab
  - notebook
  - ipython
  - ipykernel
  - quarto
  # - pip
  # - pip:
  #   - quarto
